composer.json
See https://github.com/nelmio/NelmioSecurityBundle/issues/197
=> We are currently not compatible with twig 2.7

README.md
Should be
```
composer require contao/conflicts:@dev
```
instead of
```
composer require contao/conflicts @dev
```
=> fix composer require command

composer.json
See: https://github.com/symfony/symfony/pull/31108#issuecomment-484199474
It looks like it will be fixed in 4.2.8 (https://github.com/symfony/symfony/pull/31154)
=> Added `symfony/framework-bundle` 4.2.7

composer.json
As discussed in https://github.com/contao/contao/issues/2495#issuecomment-728769074
=> Conflict with scssphp/scssphp 1.4

composer.json
See https://github.com/scheb/2fa/issues/51
=> Adjust conflict as 5.4.1 is compatible again

composer.json
See https://github.com/contao/conflicts/pull/16#issuecomment-766692104
=> Removed conflict with scheb/2fa-bundle again

composer.json
As discussed in https://github.com/contao/conflicts/pull/19#issuecomment-771089419
=> Revert the conflict with lobucci/jwt

composer.json
Should be merged once https://github.com/contao/contao/pull/2929 got released (for 4.9 AND 4.11)
=> Revert conflict for doctrine/dbal 2.13.0

composer.json
see https://github.com/Ocramius/ProxyManager/issues/702 it's a problem when composer < 2.0.14
=> Update fail by Ocramius/proxy-manager in 2.12.0

composer.json
See https://github.com/contao/conflicts/pull/26#issuecomment-857523349
=> Revert conflict for ocramius/proxy-manager

composer.json
Because https://github.com/doctrine/DoctrineBundle/pull/1488
=> Add a conflict for doctrine/doctrine-bundle:2.6.0

composer.json
See https://github.com/contao/contao/issues/5251
Downgrading `symfony/http-kernel` to `5.4.11` helps.
=> Add a conflict for symfony/http-kernel: 5.4.12

composer.json
See https://github.com/doctrine/dbal/pull/5779#issuecomment-1288154013
=> Conflict with doctrine/dbal 3.5.0

composer.json
=> Conflict with symfony/dependency-injection 6.0.16 and 6.1.8 (see #40)

composer.json
See https://github.com/contao/contao/actions/runs/3586421756/jobs/6035594582
=> Conflict with symfony/dependency-injection 6.2.0 (see #41)

composer.json
See https://github.com/contao/contao/issues/5693
=> Add conflict for lcobucci/jwt > 4.2.0

composer.json
See https://github.com/contao/contao/issues/6257
I have debugged it and was able to verify that the finder component causes the issue: https://github.com/symfony/symfony/issues/51162#issuecomment-1657221965
=> Conflict with symfony/finder 5.4.26, 6.2.13 and 6.3.2

composer.json
See https://github.com/contao/contao/issues/6409
=> Conflict with `doctrine/dbal: 3.7.0`

composer.json
See https://github.com/contao/contao/issues/6983#issuecomment-1985543049
=> Remove the `lcobucci/jwt` conflict

composer.json
knplabs/knp-menu-bundle 3.4.0 breaks the Contao backend
There is already an issue for this: https://github.com/KnpLabs/KnpMenuBundle/issues/476
https://github.com/contao/contao/issues/7118
```
Twig\Error\LoaderError:
Template "@KnpMenu/menu.html.twig" is not defined.
at vendor/contao/core-bundle/templates/Backend/be_menu.html.twig:13
at Twig\Loader\ChainLoader->getCacheKey()
(vendor/twig/twig/src/Environment.php:264)
at Twig\Environment->getTemplateClass()
(vendor/twig/twig/src/Environment.php:312)
at Twig\Environment->load()
(vendor/twig/twig/src/Environment.php:280)
at Twig\Environment->render()
(vendor/knplabs/knp-menu/src/Knp/Menu/Renderer/TwigRenderer.php:41)
at Knp\Menu\Renderer\TwigRenderer->render()
(vendor/knplabs/knp-menu/src/Knp/Menu/Twig/Helper.php:77)
at …
```
=> Add conflict for knplabs/knp-menu-bundle 3.4.0

composer.json
Reverts part of https://github.com/contao/conflicts/pull/63
Should be merged once https://github.com/contao/contao/pull/7123 and https://github.com/contao/contao/pull/7122 got released.
=> Revert 3.9.* Twig conflict

composer.json
Both our issues are fixed in version 5.1.3
=> Allow version 5.1.3 of web-auth/webauthn-symfony-bundle

composer.json
https://github.com/php-feed-io/feed-io/issues/23
=> Add a conflict for `php-feed-io/feed-io` `6.1.1`
