contao/conflicts

composer.json
See https://github.com/contao/contao/pull/707
Somehow 2FA is broken with `scheb/two-factor-bundle` in version `4.7.0` (never ending redirects after submitting the verify code). I need to investigate why.
=> Add conflict with scheb/two-factor-bundle 4.7.0 (broken 2FA in frontend)

composer.json
Broken 2FA in frontend, see #6
This reverts commit f450dd170bb31d44e82622d487788914f8bce648 and should be merged after https://github.com/contao/contao/pull/711 has been released.
=> Revert "Add conflict with scheb/two-factor-bundle 4.7.0"

composer.json
This PR reverts the changes from 87a15666b34d7813f95c75438ba0f9c2ba525619 as Contao 4.8.8 has been released today (see contao/contao#1140).
=> Revert the knp-time-bundle conflict

composer.json
See https://github.com/contao/contao/pull/2680. Has to be reverted, when https://github.com/contao/contao/pull/2680 is released.
=> Add conflict with scheb/2fa-bundle >=5.4

composer.json
This should no longer be needed, see https://github.com/contao/contao/issues/978#issuecomment-559522920
And we need to remove this in order to allow monolog 2 to be installed with Contao 4.11
=> Remove monolog 2 conflict

composer.json
See https://github.com/contao/contao-manager/issues/625#issue-797746482
Until this is resolved on the Composer Cloud Resolver a conflict could be added here, so that `lcobucci/jwt: 4.1.*` will not be installed.
_Note:_ this only affects installations using the Contao Manager together with the Composer Cloud Resolver. Otherwise Composer will of course not try to install  `lcobucci/jwt: 4.1.*`, if your environment does not have `ext-sodium` enabled.
=> Add conflict for lcobucci/jwt

composer.json
see https://github.com/symfony/symfony/issues/40618
Should be set to an exact version once this is fixed in Symfony
=> Disallow installation of Sf FrameworkBundle 5.2.6

composer.json
do not use `doctrine/dbal` in version 2.13.0
=> Add conflict for doctrine/dbal 2.13.0

composer.json
Due to type error in the `Request` class introduced in `4.4.27`. See https://github.com/symfony/symfony/pull/42289
=> Add symfony/http-foundation: 4.4.27

composer.json
It seems that Symfony has messed up an upstream merge and now symfony/translation 5.3.8 no longer is PSR-4 compatible. This breaks Contao from version 4.9 upwards.
=> Add a conflict for symfony/translation

composer.json
Symfony has removed the broken tags, therefore we could remove the conflicts again. @contao/developers WDYT?
=> Remove the latest conflicts again

composer.json
With the changes of https://github.com/symfony/http-kernel/commit/56df45cd80512e6bb69ea96095e5e430448d0640 which was released in Symfony `5.4.1` logins via `http://` do not work anymore. See also https://github.com/symfony/symfony/issues/44546
=> Add conflict for symfony/http-kernel 5.4.1

composer.json
See https://github.com/contao/contao/issues/3980
I think it's better to immediately add that conflict, as it reflects poorly on the performance of Contao 4.13-RC.
=> Add doctrine/dbal 3.3.0

composer.json
This adds a conflict for `symfony/web-profiler-bundle` due to https://github.com/symfony/symfony/pull/46650 - see https://github.com/contao/manager-plugin/issues/48
Once the `contao/manager-plugin` unlocks Symfony 6, the fixed version of `symfony/web-profiler-bundle` can automatically be installed (without removing this conflict).
=> Add a conflict for symfony/web-profiler-bundle

composer.json
In the newest Symfony versions the [`Content-Type` auto-detection for `BinaryFileResponse` is broken](https://github.com/symfony/symfony/pull/47746), resulting in every response (where you do not set the `Content-Type` manually) having a `Content-Type` of `text/html`.
This is also reproducible in Contao:
1. Execute `contao:automator purgeImageCache`.
2. Open the developer tools of your browser and head to the network tab.
3. Refresh a front end page with images (produced by image sizes).
4. Inspect the response headers for the newly generated image files - they will have `text/html` instead of `image/jpeg` etc. for their `Content-Type`.
While this in particular is not a huge issue, as browsers react quite lenient here apparently (though the preview of the developer tools will not show the …
=> Add more conflicts for symfony/http-foundation

composer.json
Updating `php-http/discovery` to `1.15.0` (and then confirming the execution of its composer plugin) currently results in an endless composer update loop. See https://github.com/php-http/discovery/issues/211
=> Add `"php-http/discovery": "1.15.0"`

composer.json
Original [error](https://github.com/php-http/message/pull/152#issuecomment-1550923764) fixed via https://github.com/FriendsOfSymfony/FOSHttpCache/pull/543.
=> Remove `php-http/message` conflict

composer.json
Version 3.3.0 seems to have a (may be unintentional) BC break in it:
```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function League\FlysystemBundle\Adapter\AdapterDefinitionFactory::createDefinition(), 2 passed in vendor\contao\contao\core-bundle\src\DependencyInjection\Filesystem\FilesystemConfiguration.php on line 91 and exactly 3 expected in vendor\league\flysystem-bundle\src\Adapter\AdapterDefinitionFactory.php:43
```
=> Conflict with `league/flysystem-bundle 3.3.0`

composer.json
After upgrading to `symfony/framework-bundle: 5.4.30` the `prod` logs will be flooded with deprecation messages, whenever an `ERROR` or `CRITICAL` log entry happens to be logged (`fingers_crossed`). This can cause high memory and storage loads.
=> Conflict with `symfony/framework-bundle: 5.4.30`

composer.json
Symfony `5.4.31` was released today, which causes #52 again. I think until we got to the bottom of this we need to use an open ended conflict.
=> Add more conflicts for `symfony/framework-bundle`

composer.json
The `5.4.30 - 5.4.32 || 6.3.6 - 6.3.9` conflicts can be removed, once https://github.com/contao/contao/pull/6574 is merged and released.
=> Increase conflicted versions for `symfony/framework-bundle`

composer.json
https://github.com/contao/contao/issues/7121
Or should we conflict `3.9.*` in general as long as we have not released https://github.com/contao/contao/pull/7122 ?
=> Add conflict for `twig/twig` `3.9.*`

composer.json
It looks like there are still some issues with Twig 3.9.
At least the `PhpTemplateProxyNode` needs to be updated as well. PR will follow.
=> Conflict with Twig 3.9.*

composer.json
As `twig/intl-extra` has the wrong dependency on `twig/twig` in version 3.9.0 (see https://github.com/twigphp/intl-extra/commit/39865e5d13165016a8e7ab8cc648ad2f7aa4b639 ) we have to conflict with it as well to prevent errors like `Call to undefined method Twig\Extension\CoreExtension::dateConverter()`.
=> Conflict with twig/intl-extra 3.9.0

composer.json
The recently released twig version adds new deprecations:
https://github.com/twigphp/Twig/compare/v3.9.3...v3.10.0
```In EscaperExtension.php line 127:                                            
You must call "setEnvironment()" before calling "Twig\Extension\EscaperExtension::setEscaper()".
```
=> Add conflict with twig 3.10.0

composer.json
We might need to fix [this](https://github.com/twigphp/Twig/issues/4087) in Contao (depending on whether this will be considered a BC break by Twig or not). Until then we need to conflict with `twig/twig: 3.10.*`.
=> Add a conflict for `twig/twig` `3.10.*`

composer.json
We should remove the conflict with the open version constraint once the issue was fixed.
See #69 and #70
With https://github.com/twigphp/Twig/pull/4088 this should get fixed probably.
=> Revert the Twig 3.10.* conflict

composer.json
Currently the following error occurs when installing/updating Contao 5:
```
The "contao_manager.plugin_loader" service is synthetic, it needs to be set at boot time before it can be used.
```
Downgrading `symfony/http-kernel` fixes the issue.
=> Add a conflict for `symfony/http-kernel` `6.4.9`

composer.json
See https://github.com/contao/conflicts/pull/72
I missed that Contao 5.3 already also allows `symfony/http-kernel` `^7.0`.
=> Add a conflict for `symfony/http-kernel` `7.1.2`

composer.json
See https://github.com/web-auth/webauthn-framework/pull/707
```
In DefinitionErrorExceptionPass.php line 48:
Cannot autowire service "Webauthn\Bundle\Security\Authentication\WebauthnBadgeListener": argument "$userProvider" of method "__construct()"
references interface "Symfony\Component\Security\Core\User\UserProviderInterface" but no such service exists. You should maybe alias this interface to
one of these existing services: "security.user_providers", "contao.security.backend_user_provider", "contao.security.frontend_user_provider".
```
=> Add a conflict for web-auth/webauthn-symfony-bundle 5.2.0
